# HTTP HEADERS - Client Role 의 토큰
{
  "x-jwt": "JWT TOKEN ~~~"
}

mutation {
  createOrder(
    input: {
      restaurantId: 4
      items: [
        {
          dishId: 7
          options: [
            { name: "Spice Level", choice: "Kill Me" }
            { name: "Size", choice: "XL", extra: 5 }
          ]
        }
      ]
    }
  ) {
    error
    ok
  }
}

mutation {
  editOrder(input: {
    id: 12,
    status: Cooked
  }) {
    error
    ok
  }
}

mutation {
  takeOrder(input: {
    id: 12
  }) {
    error
    ok
  }
}