# HTTP HEADERS - Client Role 의 토큰
{
  "X-JWT": "JWT TOKEN ~~~"
}

mutation {
  createOrder(
    input: {
      restaurantId: 2
      items: [
        {
          dishId: 4
          options: [
            { name: "Spice Level", choice: { name: "Kill Me" } }
            { name: "Size", choice: { name: "XL", extra: 5 } }
          ]
        }
      ]
    }
  ) {
    error
    ok
  }
}
